### ISSUE TITLE
Height adjusting with flexbox when flex-direction: column

### ISSUE THREAD

**Issue by juhapekkamoilanen** [juhapekkamoilanen/kanbahn#1]
Setting flex-container height to auto causes the container to fit all item on one column:

![all-items-in-one-column](https://user-images.githubusercontent.com/16867703/37756443-302541ae-2db2-11e8-8777-afed410dc307.png)

Instead the container should behave like this:

![items-in-two-columns](https://user-images.githubusercontent.com/16867703/37756511-6d3942fc-2db2-11e8-95f5-19625635e0e2.png)

Now the height has to be explicitly set:

<pre>
.flex-card-wrapper {
  position: relative;
  display: flex;
  flex-direction: column;
  flex-wrap: wrap-reverse;
  box-sizing: border-box;
  width: 100%;
  padding: var(--default-margin);
  <b>height: 200px;</b>
  overflow: hidden;
</pre>

How to properly auto-adjust the height?

**Comment by emlai** [comment]
According to [this](https://codepen.io/townivan/post/flexbox-flex-direction-column) it's not possible to column-wrap in a dynamic-height container with flex. Also I couldn't find anything on how to accomplish this, so I think they're right.

**Comment by emlai** [comment]
I'd say let's use `flex-direction: row;` and `flex-wrap: wrap;`, that way the flex container can have a dynamic height.
